---
- hosts: all
  become: true
  tasks:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: https://getfedora.org/static/352C64E5.txt
    - name: install the latest version of ansible
      yum:
        name: ansible
        state: latest    