---
- hosts: all
  become: true
  tasks:
    - name: upload vagrant master user ssh key
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', 'tmp/id_rsa.tmp') }}"